### ISSUE TITLE
devices module

### ISSUE THREAD

**Issue by robinvy** [ansible-aix/ansible-power-aix#32]
Create the community module for the devices management.

**Comment by kavanabhat** [comment]
Functionalities of cfgmgr/chdev/rmdev commands will be covered by this module. 
Also, the features of community module aix_devices will be considered. (https://docs.ansible.com/ansible/latest/modules/aix_devices_module.html)

**Comment by robinvy** [comment]
- Fixed flake8 complaints from TravisCI build: use `==/!=` instead of `is/is not` to compare strings. ([https://github.com/ansible-aix/ansible-power-aix/commit/75a83043b021b676b7db99117c336012252eb195](https://github.com/ansible-aix/ansible-power-aix/commit/75a83043b021b676b7db99117c336012252eb195)). Note it didn't appear locally on my system, I guess the version of flake8 differs with the one TravisCI is using.
- Added the return inline documentation bloc for ansible-doc-extractor to work: ([https://github.com/ansible-aix/ansible-power-aix/commit/1c472815d0ab9d828d3d9a6801b477d35a501bef](https://github.com/ansible-aix/ansible-power-aix/commit/1c472815d0ab9d828d3d9a6801b477d35a501bef))
```
RETURN = r'''
msg:
    description: The execution message.
    returned: always
    type: str
rc':
    description: The return code.
    returned: If the command failed.
    type: int
stdout':
    description: The standard output.
    returned: If the command failed.
    type: str
stderr':
    description: The standard error.
    returned: If the command failed.
    type: str
'''
```
