### ISSUE TITLE
nim_vios_alt_disk: multiple disk per target selection

### ISSUE THREAD

**Issue by robinvy** [ansible-aix/ansible-power-aix#48]
This probably requires changing the targets attribute to a dictionary.

From
`targets: vios1,hdisk2,vios2,hdisk2`
to:
```
targets:
  vios1
    name: quimbyios1
    disks: hdisk2, hdisk3
  vios2
    name: quimbyios2
    disks: hdisk2
```

In automatic mode, we could fail if the rootvg is mirrored as it is difficult to find a set of disks matching the mirror.
