### ISSUE TITLE
New inetd role

### ISSUE THREAD

**Issue by robinvy** [ansible-aix/ansible-power-aix#67]
Can we modify this configuration file?

**Comment by dberg1** [comment]
I could not find any existing inetd module for Ansible.
If it is just a matter of modifying /etc/inetd.conf, one could use replace module to change the lines in the file.

**Comment by dberg1** [comment]
Here is an example showing how to disable telnet and ftpd on an AIX system using Ansible `replace` and `service` core modules.
```
- hosts: aix
  gather_facts: no

  handlers:
  - name: restart inetd
    service: name=inetd state=restarted
  tasks:
  - name: disable ftpd and telnet
    replace:
      path: /etc/inetd.conf
      regexp: '^(ftp\s|telnet\s)'
      replace: '#\1'
      backup: yes
      owner: root
      group: system
      mode: 0664
    notify: restart inetd
```
