### ISSUE TITLE
VIOS cluster management module (ibm.power_vios)

### ISSUE THREAD

**Issue by robinvy** [ansible-aix/ansible-power-aix#81]
Check existing module or create a new module for cluster/ssp management

As endpoint management (in power_vios collection).
As NIM management (in power_aix collection).

**Comment by dberg1** [comment]
See following VIOS ioscli commands:
- cluster
- tier
- lu
- snapshot
- failgrp

See also: https://www.ibm.com/support/knowledgecenter/POWER8/p8hb1/p8hb1_clustervioscli.htm

The idea would be to have something like:
```
cluster:
  name: mycluster
  state: present
  nodes:
  - hostname1
  - hostname2
  repopvs:
  - hdisk5
  storagepool:
    name: mysp1
    state: present
    tiers:
    - name: mytier1
      pvs:
      - hdisk1
      - hdisk2
      lus:
      - name: lu1
        size: 2G
        state: present
        mapping:
          vadapter: vhost0
      - name: lu2
        state: absent
      snapshots:
      - name: snap1
      failgrps:
      - name: fg1
        pvs:
        - hdisk3
```

With present/absent to add or remove luns, tiers etc...
